
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APPLY BSTRING CHECKEQUALS COMMA COMMUTATOR COMPOSE CONJ DEFCOMMAND DEFINEEQUALS GENCOMMAND LPAREN LSQBRACKET NEG NUMBER RPAREN RSQBRACKET VARstatement  : command\n                   | equation\n                   | expressioncommand : GENCOMMAND params\n                    | GENCOMMANDequation : VAR DEFINEEQUALS expressionexpression : expression COMPOSE expression\n               | LPAREN expression RPAREN\n               | NEG expression\n               | expression CONJ expression\n               | expression COMMUTATOR expression\n               | VAR\n               | DEFCOMMAND argsword : word APPLY expression\n                       | BSTRING args : LPAREN params RPARENlist : LSQBRACKET params RSQBRACKETparams : params COMMA param\n                      | paramparam : list \n                     | VAR\n                     | NUMBER \n                     | BSTRING'
    
_lr_action_items = {'GENCOMMAND':([0,],[5,]),'VAR':([0,5,7,8,10,11,12,19,20,25,29,],[6,16,22,22,22,22,22,16,22,16,16,]),'LPAREN':([0,7,8,9,10,11,12,20,],[7,7,7,25,7,7,7,7,]),'NEG':([0,7,8,10,11,12,20,],[8,8,8,8,8,8,8,]),'DEFCOMMAND':([0,7,8,10,11,12,20,],[9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,6,13,14,15,16,17,18,22,23,24,26,27,28,31,32,34,35,36,],[0,-1,-2,-3,-5,-12,-4,-19,-20,-21,-22,-23,-12,-9,-13,-7,-10,-11,-6,-8,-18,-17,-16,]),'COMPOSE':([4,6,21,22,23,24,26,27,28,31,32,36,],[10,-12,10,-12,10,-13,10,10,10,10,-8,-16,]),'CONJ':([4,6,21,22,23,24,26,27,28,31,32,36,],[11,-12,11,-12,11,-13,11,11,11,11,-8,-16,]),'COMMUTATOR':([4,6,21,22,23,24,26,27,28,31,32,36,],[12,-12,12,-12,12,-13,12,12,12,12,-8,-16,]),'NUMBER':([5,19,25,29,],[17,17,17,17,]),'BSTRING':([5,19,25,29,],[18,18,18,18,]),'LSQBRACKET':([5,19,25,29,],[19,19,19,19,]),'DEFINEEQUALS':([6,],[20,]),'COMMA':([13,14,15,16,17,18,30,33,34,35,],[29,-19,-20,-21,-22,-23,29,29,-18,-17,]),'RSQBRACKET':([14,15,16,17,18,30,34,35,],[-19,-20,-21,-22,-23,35,-18,-17,]),'RPAREN':([14,15,16,17,18,21,22,23,24,26,27,28,32,33,34,35,36,],[-19,-20,-21,-22,-23,32,-12,-9,-13,-7,-10,-11,-8,36,-18,-17,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'command':([0,],[2,]),'equation':([0,],[3,]),'expression':([0,7,8,10,11,12,20,],[4,21,23,26,27,28,31,]),'params':([5,19,25,],[13,30,33,]),'param':([5,19,25,29,],[14,14,14,34,]),'list':([5,19,25,29,],[15,15,15,15,]),'args':([9,],[24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> command','statement',1,'p_statement','engine.py',102),
  ('statement -> equation','statement',1,'p_statement','engine.py',103),
  ('statement -> expression','statement',1,'p_statement','engine.py',104),
  ('command -> GENCOMMAND params','command',2,'p_command','engine.py',108),
  ('command -> GENCOMMAND','command',1,'p_command','engine.py',109),
  ('equation -> VAR DEFINEEQUALS expression','equation',3,'p_equation','engine.py',117),
  ('expression -> expression COMPOSE expression','expression',3,'p_expression','engine.py',122),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','engine.py',123),
  ('expression -> NEG expression','expression',2,'p_expression','engine.py',124),
  ('expression -> expression CONJ expression','expression',3,'p_expression','engine.py',125),
  ('expression -> expression COMMUTATOR expression','expression',3,'p_expression','engine.py',126),
  ('expression -> VAR','expression',1,'p_expression','engine.py',127),
  ('expression -> DEFCOMMAND args','expression',2,'p_expression','engine.py',128),
  ('word -> word APPLY expression','word',3,'p_apply','engine.py',160),
  ('word -> BSTRING','word',1,'p_apply','engine.py',161),
  ('args -> LPAREN params RPAREN','args',3,'p_args','engine.py',172),
  ('list -> LSQBRACKET params RSQBRACKET','list',3,'p_list','engine.py',176),
  ('params -> params COMMA param','params',3,'p_params','engine.py',180),
  ('params -> param','params',1,'p_params','engine.py',181),
  ('param -> list','param',1,'p_param','engine.py',188),
  ('param -> VAR','param',1,'p_param','engine.py',189),
  ('param -> NUMBER','param',1,'p_param','engine.py',190),
  ('param -> BSTRING','param',1,'p_param','engine.py',191),
]
